# docker/Dockerfile.bot

FROM node:18-alpine
WORKDIR /app

# Копируем зависимости
COPY telegram-bot/package*.json ./
RUN npm install

# Копируем код бота
COPY telegram-bot ./

EXPOSE 8080  # Если вдруг нужен порт для webhook, не всегда нужно.
CMD ["node", "bot.js"]
