# docker/Dockerfile.nextjs

FROM node:18-alpine
WORKDIR /app

# Копируем package.json и lock-файл
COPY frontend/nextjs/package*.json ./
RUN npm install

# Копируем всё приложение Next.js
COPY frontend/nextjs ./

# Сборка в production
RUN npm run build

# Expose 3000
EXPOSE 3000

# Запуск
CMD ["npm", "run", "start"]
