# docker/Dockerfile.nextjs

FROM node:18-alpine
WORKDIR /app

COPY frontend/nextjs/package*.json ./
RUN npm install

COPY frontend/nextjs ./
ENV NODE_ENV=production
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
