# docker/Dockerfile.strapi

FROM node:18-alpine
WORKDIR /app

# Копируем package.json и lock-файл
COPY backend/strapi/package*.json ./
RUN npm install

# Копируем остальной код Strapi
COPY backend/strapi ./

# Собираем админку (продакшен)
RUN npm run build

EXPOSE 1337
CMD ["npm", "run", "start"]
