FROM node:18-alpine
WORKDIR /app

# Копируем package.json / package-lock.json из telegram-bot
COPY telegram-bot/package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь код бота
COPY telegram-bot ./

# Если у вас .env внутри telegram-bot, нужно прокинуть переменные (см. env_file в docker-compose)
# Или добавить сами .env (не рекомендуется в публичный репо)

# Запускаем
CMD ["node", "bot.js"]
