version: '3.7'
services:
  db:
    image: postgres:14
    container_name: syndicate-db
    env_file:
      - ../.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  strapi:
    build:
      context: ..
      dockerfile: docker/Dockerfile.strapi
    container_name: syndicate-strapi
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    ports:
      - "1337:1337"  # Можно убрать, если будете проксировать только через Nginx
    restart: always

  nextjs:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nextjs
    container_name: syndicate-nextjs
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
    depends_on:
      - strapi
    ports:
      - "3000:3000"  # Можно убрать, если будете проксировать только через Nginx
    restart: always

  telegram-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bot
    container_name: syndicate-bot
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
    depends_on:
      - strapi
    restart: always

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.nginx
    container_name: syndicate-nginx
    depends_on:
      - nextjs
      - strapi
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Прокидываем конфиг Nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      
      # Если у вас есть SSL на хостовой машине, см. пункт о Certbot
      # - /etc/letsencrypt/live/syndicate-store.ru/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      # - /etc/letsencrypt/live/syndicate-store.ru/privkey.pem:/etc/ssl/certs/privkey.pem:ro

    restart: always

volumes:
  postgres_data:
