version: '3.8'

services:
  db:
    image: postgres:14
    container_name: syndicate-db
    environment:
      - POSTGRES_USER=synadmin
      - POSTGRES_PASSWORD=yourpass
      - POSTGRES_DB=syndicate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  strapi:
    build:
      context: ..
      dockerfile: docker/Dockerfile.strapi
    container_name: syndicate-strapi
    environment:
      - NODE_ENV=production
      # Переменные среды для Strapi
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=syndicate_db
      - DATABASE_USERNAME=synadmin
      - DATABASE_PASSWORD=yourpass
      - HOST=0.0.0.0
      - PORT=1337
    depends_on:
      - db
    restart: always

  nextjs:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nextjs
    container_name: syndicate-nextjs
    environment:
      - NODE_ENV=production
      # Если нужно, добавьте переменные окружения для Next.js
    depends_on:
      - strapi
    restart: always

  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bot
    container_name: syndicate-bot
    # Переменные среды для бота (телеграм-токен)
    environment:
      - TELEGRAM_BOT_TOKEN=7811128055:AAFvlrXpEkdfnwtPJSF2jbB8VuLyrZ0lMI0
      # или использовать env_file: ["../telegram-bot/.env"]
    depends_on:
      - strapi
    restart: always

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.nginx
    depends_on:
      - nextjs
      - strapi
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/syndicate-store.ru/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/syndicate-store.ru/privkey.pem:/etc/ssl/certs/privkey.pem:ro
    restart: always

volumes:
  postgres_data:
